export const songs = [
  {
    id: 1,
    name: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
  },
  {
    id: 2,
    name: "Imagine",
    artist: "John Lennon",
    album: "Imagine",
  },
  {
    id: 3,
    name: "Hey Jude",
    artist: "The Beatles",
    album: "Hey Jude",
  },
  {
    id: 4,
    name: "Like a Rolling Stone",
    artist: "Bob Dylan",
    album: "Highway 61 Revisited",
  },
  {
    id: 5,
    name: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
  },
  {
    id: 6,
    name: "What's Going On",
    artist: "Marvin Gaye",
    album: "What's Going On",
  },
  {
    id: 7,
    name: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
  },
  {
    id: 8,
    name: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
  },
  {
    id: 9,
    name: "Stairway to Heaven",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
  },
  {
    id: 10,
    name: "I Will Always Love You",
    artist: "Whitney Houston",
    album: "The Bodyguard",
  },
  {
    id: 11,
    name: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    album: "Appetite for Destruction",
  },
  {
    id: 12,
    name: "Yesterday",
    artist: "The Beatles",
    album: "Help!",
  },
  {
    id: 13,
    name: "Purple Rain",
    artist: "Prince",
    album: "Purple Rain",
  },
  {
    id: 14,
    name: "Let It Be",
    artist: "The Beatles",
    album: "Let It Be",
  },
  {
    id: 15,
    name: "Born to Run",
    artist: "Bruce Springsteen",
    album: "Born to Run",
  },
  {
    id: 16,
    name: "Roxanne",
    artist: "The Police",
    album: "Outlandos d'Amour",
  },
  {
    id: 17,
    name: "Lose Yourself",
    artist: "Eminem",
    album: "8 Mile",
  },
  {
    id: 18,
    name: "Respect",
    artist: "Aretha Franklin",
    album: "I Never Loved a Man the Way I Love You",
  },
  {
    id: 19,
    name: "Good Vibrations",
    artist: "The Beach Boys",
    album: "Smiley Smile",
  },
  {
    id: 20,
    name: "Johnny B. Goode",
    artist: "Chuck Berry",
    album: "Chuck Berry Is on Top",
  },
  {
    id: 21,
    name: "What's Love Got to Do with It",
    artist: "Tina Turner",
    album: "Private Dancer",
  },
  {
    id: 22,
    name: "Superstition",
    artist: "Stevie Wonder",
    album: "Talking Book",
  },
  {
    id: 23,
    name: "I Want to Hold Your Hand",
    artist: "The Beatles",
    album: "Meet the Beatles!",
  },
  {
    id: 24,
    name: "Crazy in Love",
    artist: "Beyoncé",
    album: "Dangerously in Love",
  },
  {
    id: 25,
    name: "Sweet Home Alabama",
    artist: "Lynyrd Skynyrd",
    album: "Second Helping",
  },
  {
    id: 26,
    name: "Every Breath You Take",
    artist: "The Police",
    album: "Synchronicity",
  },
  {
    id: 27,
    name: "Thriller",
    artist: "Michael Jackson",
    album: "Thriller",
  },
  {
    id: 28,
    name: "Piano Man",
    artist: "Billy Joel",
    album: "Piano Man",
  },
  {
    id: 29,
    name: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    album: "Uptown Special",
  },
  {
    id: 30,
    name: "Like a Prayer",
    artist: "Madonna",
    album: "Like a Prayer",
  },
  {
    id: 31,
    name: "Wonderwall",
    artist: "Oasis",
    album: "(What's the Story) Morning Glory?",
  },
  {
    id: 32,
    name: "Livin' on a Prayer",
    artist: "Bon Jovi",
    album: "Slippery When Wet",
  },
  {
    id: 33,
    name: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
  },
  {
    id: 34,
    name: "Let It Go",
    artist: "Idina Menzel",
    album: "Frozen",
  },
  {
    id: 35,
    name: "Rolling in the Deep",
    artist: "Adele",
    album: "21",
  },
  {
    id: 36,
    name: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
  },
  {
    id: 37,
    name: "Chandelier",
    artist: "Sia",
    album: "1000 Forms of Fear",
  },
  {
    id: 38,
    name: "Someone Like You",
    artist: "Adele",
    album: "21",
  },
  {
    id: 39,
    name: "Firework",
    artist: "Katy Perry",
    album: "Teenage Dream",
  },
  {
    id: 40,
    name: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
  },
  {
    id: 41,
    name: "Shake It Off",
    artist: "Taylor Swift",
    album: "1989",
  },
  {
    id: 42,
    name: "Take On Me",
    artist: "a-ha",
    album: "Hunting High and Low",
  },
  {
    id: 43,
    name: "Don't Stop Believin'",
    artist: "Journey",
    album: "Escape",
  },
  {
    id: 44,
    name: "Dancing Queen",
    artist: "ABBA",
    album: "Arrival",
  },
  {
    id: 45,
    name: "Toxic",
    artist: "Britney Spears",
    album: "In the Zone",
  },
  {
    id: 46,
    name: "Rolling in the Deep",
    artist: "Adele",
    album: "21",
  },
  {
    id: 47,
    name: "Wake Me Up",
    artist: "Avicii",
    album: "True",
  },
  {
    id: 48,
    name: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    album: "Uptown Special",
  },
  {
    id: 49,
    name: "Radioactive",
    artist: "Imagine Dragons",
    album: "Night Visions",
  },
  {
    id: 50,
    name: "Old Town Road",
    artist: "Lil Nas X",
    album: "7 EP",
  },
];
